export interface CityData {
  slug: string;
  name: string;
  state: string;
  stateCode: string;
  geoRegion: string;
  latitude: number;
  longitude: number;
  population: string;
  neighborhoods: string[];
  industries: string[];
  localAngle: string;
  priceRange: string;
}

export const cities: CityData[] = [
  {
    slug: "new-york",
    name: "New York City",
    state: "New York",
    stateCode: "NY",
    geoRegion: "US-NY",
    latitude: 40.7128,
    longitude: -74.006,
    population: "8.3M",
    neighborhoods: ["Manhattan", "Brooklyn", "Queens", "Bronx", "Midtown", "SoHo", "Tribeca", "Financial District"],
    industries: ["Finance", "Media", "Tech", "Fashion", "Real Estate", "Healthcare"],
    localAngle: "Serving Fortune 500 companies and ambitious startups in the city that never sleeps.",
    priceRange: "$$",
  },
  {
    slug: "san-francisco",
    name: "San Francisco",
    state: "California",
    stateCode: "CA",
    geoRegion: "US-CA",
    latitude: 37.7749,
    longitude: -122.4194,
    population: "874K",
    neighborhoods: ["SOMA", "Mission District", "Financial District", "Marina", "Oakland", "Berkeley", "Palo Alto", "San Jose"],
    industries: ["Tech", "Startups", "Venture Capital", "Biotech", "SaaS"],
    localAngle: "Oakland native. Silicon Valley experience. Building AI systems for the world's most innovative companies.",
    priceRange: "$$",
  },
  {
    slug: "los-angeles",
    name: "Los Angeles",
    state: "California",
    stateCode: "CA",
    geoRegion: "US-CA",
    latitude: 34.0522,
    longitude: -118.2437,
    population: "4M",
    neighborhoods: ["Hollywood", "Beverly Hills", "Santa Monica", "Venice", "Downtown LA", "Culver City", "Burbank", "Pasadena"],
    industries: ["Entertainment", "Media", "Creator Economy", "Tech", "Fashion", "Healthcare"],
    localAngle: "50+ TV credits with VH1, MTV, Hallmark, Food Network. Entertainment industry expertise meets AI automation.",
    priceRange: "$$",
  },
  {
    slug: "miami",
    name: "Miami",
    state: "Florida",
    stateCode: "FL",
    geoRegion: "US-FL",
    latitude: 25.7617,
    longitude: -80.1918,
    population: "467K",
    neighborhoods: ["Miami Beach", "Brickell", "Wynwood", "Coconut Grove", "Coral Gables", "Downtown Miami", "Design District", "South Beach"],
    industries: ["Finance", "Real Estate", "Crypto/Web3", "Healthcare", "International Trade", "Tourism"],
    localAngle: "Based in Miami Beach. Available for in-person strategy sessions. Local expertise with global reach.",
    priceRange: "$$",
  },
  {
    slug: "atlanta",
    name: "Atlanta",
    state: "Georgia",
    stateCode: "GA",
    geoRegion: "US-GA",
    latitude: 33.749,
    longitude: -84.388,
    population: "498K",
    neighborhoods: ["Buckhead", "Midtown", "Downtown", "Decatur", "Sandy Springs", "Alpharetta", "Marietta"],
    industries: ["Entertainment", "Healthcare", "Tech", "Logistics", "Film/TV Production"],
    localAngle: "TV production credits with BET. Black entrepreneurship hub. Building systems for Atlanta's rising business community.",
    priceRange: "$$",
  },
  {
    slug: "austin",
    name: "Austin",
    state: "Texas",
    stateCode: "TX",
    geoRegion: "US-TX",
    latitude: 30.2672,
    longitude: -97.7431,
    population: "978K",
    neighborhoods: ["Downtown", "East Austin", "South Congress", "Domain", "Mueller", "Round Rock", "Cedar Park"],
    industries: ["Tech", "Startups", "Music", "Film", "Healthcare"],
    localAngle: "Serving Austin's booming tech scene. From podcasters to unicorn startups.",
    priceRange: "$$",
  },
  {
    slug: "chicago",
    name: "Chicago",
    state: "Illinois",
    stateCode: "IL",
    geoRegion: "US-IL",
    latitude: 41.8781,
    longitude: -87.6298,
    population: "2.7M",
    neighborhoods: ["Loop", "River North", "Lincoln Park", "Wicker Park", "Gold Coast", "West Loop", "Naperville", "Evanston"],
    industries: ["Finance", "Manufacturing", "Healthcare", "Tech", "Food & Beverage"],
    localAngle: "Midwest work ethic meets cutting edge AI. Building systems for Chicago's established businesses and ambitious startups.",
    priceRange: "$$",
  },
  {
    slug: "dallas",
    name: "Dallas",
    state: "Texas",
    stateCode: "TX",
    geoRegion: "US-TX",
    latitude: 32.7767,
    longitude: -96.797,
    population: "1.3M",
    neighborhoods: ["Uptown", "Downtown", "Deep Ellum", "Bishop Arts", "Plano", "Frisco", "Irving", "Fort Worth"],
    industries: ["Finance", "Tech", "Healthcare", "Energy", "Real Estate"],
    localAngle: "Big business, bigger ambitions. AI automation for Dallas's high growth companies.",
    priceRange: "$$",
  },
  {
    slug: "houston",
    name: "Houston",
    state: "Texas",
    stateCode: "TX",
    geoRegion: "US-TX",
    latitude: 29.7604,
    longitude: -95.3698,
    population: "2.3M",
    neighborhoods: ["Downtown", "Galleria", "Montrose", "Heights", "Midtown", "The Woodlands", "Sugar Land", "Katy"],
    industries: ["Energy", "Healthcare", "Aerospace", "Manufacturing", "Tech"],
    localAngle: "Energy capital meets AI innovation. Automating Houston's most complex industries.",
    priceRange: "$$",
  },
  {
    slug: "boston",
    name: "Boston",
    state: "Massachusetts",
    stateCode: "MA",
    geoRegion: "US-MA",
    latitude: 42.3601,
    longitude: -71.0589,
    population: "685K",
    neighborhoods: ["Back Bay", "Beacon Hill", "South End", "Seaport", "Cambridge", "Somerville", "Brookline"],
    industries: ["Biotech", "Healthcare", "Education", "Finance", "Tech"],
    localAngle: "Where innovation meets institution. AI systems for Boston's biotech, healthcare, and tech leaders.",
    priceRange: "$$",
  },
];

export const services = [
  {
    slug: "ai-automation",
    name: "AI Automation",
    description: "ChatGPT, Claude, GoHighLevel, Make.com, Zapier automation systems",
    longDescription: "Custom AI automation systems that reduce overhead by 40% and scale output without scaling stress. ChatGPT and Claude integration, GoHighLevel CRM automation, Make.com and Zapier workflows.",
    keywords: ["AI automation", "ChatGPT", "Claude AI", "GoHighLevel", "Make.com", "Zapier", "business automation"],
    benefits: ["40% overhead reduction", "Save 20+ hours/week", "Scale without hiring", "24/7 automated operations"],
    priceRange: "$2,500 - $15,000+",
  },
  {
    slug: "revenue-systems",
    name: "Revenue Systems",
    description: "CRM automation, sales funnels, lead generation, revenue operations",
    longDescription: "Revenue system architecture that turns attention into income. CRM automation, sales funnel design, lead generation systems, and revenue operations consulting.",
    keywords: ["revenue systems", "CRM automation", "sales funnels", "lead generation", "revenue operations"],
    benefits: ["3x average revenue growth", "Automated lead follow-up", "Reduced sales cycle", "Predictable pipeline"],
    priceRange: "$5,000 - $25,000+",
  },
  {
    slug: "vibe-coding",
    name: "VibeCoding",
    description: "No-code AI development, v0.dev, Cursor, natural language programming",
    longDescription: "Build apps without writing code using natural language and AI. v0.dev, Cursor, and Claude expert. Train your team to ship software with their voice.",
    keywords: ["vibe coding", "VibeCoding", "no-code", "AI development", "v0.dev", "Cursor AI"],
    benefits: ["Build apps in hours", "No coding required", "Ship 10x faster", "Reduce dev costs 80%"],
    priceRange: "$1,500 - $10,000+",
  },
  {
    slug: "fractional-coo",
    name: "Fractional COO",
    description: "Part-time executive operations leadership, startup COO services",
    longDescription: "Fractional COO services for growing companies. Executive-level operations leadership without the full-time cost. Process optimization, team scaling, operational excellence.",
    keywords: ["fractional COO", "part-time COO", "operations consultant", "startup COO"],
    benefits: ["Executive expertise", "Fraction of the cost", "Scalable operations", "Process optimization"],
    priceRange: "$5,000 - $15,000/month",
  },
];
